In [1]:
from cell import *
from matrix import *

In [2]:
matrix_size = (50, 50)
ones_matrix = np.ones(matrix_size)
twos_matrix = np.ones(matrix_size) * 2
data_matrix = Matrix.run_simple_parameter_sweep(1, 0.0, 1.0, 101, twos_matrix, 0, False, 0, 0, True)


In [10]:
data_matrix

x_values = np.linspace(0, 100, 101)
y_values_burn_time = np.zeros_like(x_values)
for i in data_matrix:
    for j in data_matrix[i]:
        y_values_burn_time[int(i * 100)] += j.burn_time
    y_values_burn_time[int(i * 100)] /= len(data_matrix[i])
y_values_burn_time

array([  1.,   1.,   1.,   1.,   1.,   2.,   3.,   1.,   3.,   2.,   2.,
         1.,   1.,   3.,  12.,   1.,  10.,  10.,   1.,   7.,   3.,  19.,
         4.,  22.,   2.,  78.,  91.,  70., 167.,   0.,  87.,  67.,  55.,
         2.,  62.,  48.,  48.,  59.,  60.,  46.,  53.,  51.,  67.,  58.,
        60.,  52.,  53.,  53.,  40.,  35.,  40.,  59.,  58.,  56.,  51.,
        54.,  33.,  94.,   0.,  36.,  36.,  49.,  47.,  54.,  47.,  49.,
        46.,  39.,  46.,  42.,  47.,  46.,  37.,  49.,  49.,  33.,  37.,
        39.,  44.,  38.,  46.,  46.,  39.,  39.,  52.,  37.,  37.,  46.,
        49.,  46.,  49.,  40.,  48.,  37.,  49.,  35.,  46.,  47.,  34.,
        35.,  49.])

In [5]:
for i in data_matrix:
    print(f"\nP_burn = {i}\n")
    for j in data_matrix[i]:
        print(j)


P_burn = 0.0

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 1

P_burn = 0.01

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 1

P_burn = 0.02

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 1

P_burn = 0.03

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 1

P_burn = 0.04

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 1

P_burn = 0.05

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
Burn Time: 2

P_burn = 0.06

Matrix: 
[[2 2 2 ... 2 2 2]
 [2 2 2 .